spring:
  datasource:
    url: jdbc:mysql://${DB_URL}:3306/${DB_DATABASE}?useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver