name: main-to-eb

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DB_URL: ${{ secrets.DB_URL }}
  DB_DATABASE: ${{ secrets.DB_DATABASE }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

on:
  push:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.1.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: simple-spring-mvc
          path: build/libs/simple_spring_mvc-0.0.1-SNAPSHOT.jar

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.1.0

      - name: Get current time
        uses: josStorer/get-current-time@v2.1.1
        id: current-time
        with:
          format: YYYYMMDDTHHmm
          utcOffset: "+09:00"

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: simple-spring-mvc
          path: simple-spring-mvc/build/libs

      - name: Generate deployment package
        run: |
          mkdir -p deploy
          cp simple-spring-mvc/build/libs/simple_spring_mvc-0.0.1-SNAPSHOT.jar deploy/simple-spring-mvc.jar
          cp ./eb/Procfile deploy/Procfile
          cp -r ./eb/.ebextensions deploy/.ebextensions
          cd deploy && zip -r simple-spring-mvc-label-${{steps.current-time.outputs.formattedTime}}-${{github.sha}} .

      - name: Deploy Consumer to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: simple-spring-mvc
          environment_name: Simple-spring-mvc-env
          version_label: simple-spring-mvc-label-${{steps.current-time.outputs.formattedTime}}-${{github.sha}}
          region: ap-northeast-2
          deployment_package: deploy/simple-spring-mvc-label-${{steps.current-time.outputs.formattedTime}}-${{github.sha}}.zip
          wait_for_environment_recovery: 300
